-- Auto-cancel abandoned draft orders — NO-OP (superseded by 0034).
--
-- The original 0017 wrapped CREATE EXTENSION pg_cron + cancel_abandoned_drafts()
-- + cron.schedule() in one transaction. pg_cron isn't installed on Supabase, so
-- CREATE EXTENSION failed and the whole transaction rolled back — this migration
-- never actually applied on any environment.
--
-- It is neutralized here (rather than left as-is) so a fresh, in-order migration
-- run doesn't hit the failing CREATE EXTENSION and block everything after it.
-- The cancel_abandoned_drafts() function now lives in
-- 0034_cancel_abandoned_drafts_fn.sql (standalone, no extension dependency), and
-- the daily schedule is a Deno.cron job in apps/gateway/src/index.ts.
--
-- Intentionally empty (comments only) — applying this file is a no-op.
